name: "Publish Manually"

on:
  workflow_dispatch:
    inputs:
      provider:
        type: choice
        description: Choose the provider you want to publish
        options:
          - "amazon-ebs"
          - "digitalocean"
        required: true

env:
  PACKER_VERSION: "latest"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

jobs:
  publishing:
    name: publishing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup `packer`
      uses: hashicorp/setup-packer@main
      with:
        version: ${{ env.PACKER_VERSION }}

    - name: Run `packer init`
      run: "packer init ."

    - name: Run `packer build`
      run: "packer build -only ${{ github.event.inputs.provider }}.debian ."
