name: Publish images to the cloud providers using Packer

on:
  push:
    tags:
      - v*

env:
  PACKER_VERSION: "latest"
  DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  publishing:
    name: publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup `packer`
      uses: hashicorp/setup-packer@main
      with:
        version: ${{ env.PACKER_VERSION }}

    - name: Run `packer init`
      run: "packer init ."

    - name: Run `packer validate`
      run: "packer validate ."

    - name: Run `packer build`
      run: "packer build ."
